version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_USER: root
            MYSQL_DATABASE: proit_test
            MYSQL_ROOT_PASSWORD: root
        proit_test:
           image: mysql:5.7
            volumes:
            - ./mysql:db-backup/.d
            environment:
                    MYSQL_USER: root
                    MYSQL_DATABASE: proit_test
                    MYSQL_ROOT_PASSWORD: root
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
          - mysql:mysql
        ports:
          - 8001:80
        environment:
          PMA_HOST: mysql
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root      
          MYSQL_DATABASE: proit_test
